name:                AdventOfCode2015
version:             0.1.0.0
github:              "jirkamarsik/AdventOfCode2015"
license:             BSD3
author:              "Jirka Marsik"
maintainer:          "jiri.marsik89@gmail.com"
copyright:           "Copyright (C) 2017-2017 Jiri Marsik"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            My Advent of Code 2015 solutions in Haskell
category:            Exercises

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/jirkamarsik/AdventOfCode2015#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- Hoed
- parsec
- pureMD5

library:
  source-dirs: Lib

_generic-executable: &generic-executable
  main:         Main.hs
  dependencies: [AdventOfCode2015]
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  Day04:
    <<: *generic-executable
    source-dirs: Day04
  Day07:
    <<: *generic-executable
    source-dirs: Day07
